/**
 * Client-side plain-text export.
 * Converts ParsedResume data to a clean, formatted .txt file
 * that mirrors what the AI actually output.
 */
export function exportToTXT(data: ParsedResume, filename = "optimized-resume.txt"): void {
  const lines: string[] = [];

  const divider = (char = "─", len = 60) => lines.push(char.repeat(len));
  const blank = () => lines.push("");
  const section = (title: string) => {
    blank();
    lines.push(title.toUpperCase());
    divider();
  };

  // Header
  lines.push(data.fullName || "Your Name");
  const c = data.contactInfo;
  if (c) {
    const contactParts = [c.email, c.phone, c.location].filter(Boolean);
    if (contactParts.length) lines.push(contactParts.join("  ·  "));
    const linkParts = [c.linkedin, c.portfolio].filter(Boolean);
    if (linkParts.length) lines.push(linkParts.join("  ·  "));
  }
  blank();
  divider("═");

  // Summary
  if (data.summary) {
    section("Professional Summary");
    lines.push(data.summary);
  }

  // Skills
  if (data.skills?.length) {
    section("Skills");
    lines.push(data.skills.join("  ·  "));
  }

  // Experience
  if (data.experience?.length) {
    section("Experience");
    for (const exp of data.experience) {
      blank();
      lines.push(`${exp.title}  |  ${exp.company}`);
      lines.push(exp.duration);
      for (const bullet of exp.bullets) {
        lines.push(`  • ${bullet}`);
      }
    }
  }

  // Projects
  if (data.projects?.length) {
    section("Projects");
    for (const proj of data.projects) {
      blank();
      const tech = proj.technologies?.length ? `  —  ${proj.technologies.join(", ")}` : "";
      lines.push(`${proj.name}${tech}`);
      if (proj.description) lines.push(`  ${proj.description}`);
      for (const bullet of proj.bullets) {
        lines.push(`  • ${bullet}`);
      }
    }
  }

  // Education
  if (data.education?.length) {
    section("Education");
    for (const edu of data.education) {
      blank();
      lines.push(`${edu.degree}  |  ${edu.institution}`);
      lines.push(edu.year);
      if (edu.details) lines.push(`  ${edu.details}`);
    }
  }

  // Certifications
  if (data.certifications?.length) {
    section("Certifications");
    for (const cert of data.certifications) {
      lines.push(`  • ${cert}`);
    }
  }

  // Achievements
  if (data.achievements?.length) {
    section("Achievements");
    for (const ach of data.achievements) {
      lines.push(`  • ${ach}`);
    }
  }

  blank();
  divider("═");
  lines.push(`Generated by Resumate · ${new Date().toLocaleDateString()}`);

  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Exports the full raw AI optimization result as a JSON file.
 * Includes the parsed resume, changelog, and ATS score.
 */
export function exportToJSON(optimization: ResumeOptimization, filename = "optimized-resume.json"): void {
  const output = {
    exportedAt: new Date().toISOString(),
    atsScoreEstimate: optimization.optimized.atsScoreEstimate,
    theme: optimization.optimized.theme,
    changeLog: optimization.optimized.changeLog ?? [],
    suggestedAdditions: optimization.optimized.suggestedAdditions ?? [],
    parsedResume: optimization.optimized.parsed,
  };

  const blob = new Blob([JSON.stringify(output, null, 2)], { type: "application/json;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
