import { useState, useEffect } from "react";
import Navbar from "~/components/Navbar";
import { useAppStore } from "~/lib/store";
import { useNavigate } from "react-router";
import { buildResumeFromScratch, type BuildProgress } from "~/lib/resume-builder";
import OptimizedResumeView from "~/components/OptimizedResumeView";
import PaywallModal from "~/components/PaywallModal";
import { checkPremiumStatus, useBuildCredit } from "~/lib/premium";

export const meta = () => ([
  { title: "Resumate — AI Resume Builder" },
  { name: "description", content: "Build a highly optimized resume from scratch using AI." },
]);

export default function BuildResume() {
  const { isAuthenticated, isLoading, user } = useAppStore();
  const navigate = useNavigate();
  
  const [step, setStep] = useState(1);
  const [isBuilding, setIsBuilding] = useState(false);
  const [progress, setProgress] = useState<BuildProgress | null>(null);
  const [result, setResult] = useState<ResumeOptimization | null>(null);
  const [error, setError] = useState("");
  
  // Credits and Paywall state
  const [bldCredits, setBldCredits] = useState(0);
  const [showPaywall, setShowPaywall] = useState(false);

  // Form State
  const [formData, setFormData] = useState({
    fullName: "", email: "", phone: "", location: "", linkedin: "",
    targetJob: "", jobDescription: "", summary: "",
    skills: "",
    experience: [{ id: 1, title: "", company: "", duration: "", details: "" }],
    education: [{ id: 1, degree: "", institution: "", year: "" }],
    projects: [{ id: 1, name: "", technologies: "", details: "" }]
  });

  const loadCredits = () => {
    checkPremiumStatus().then(status => setBldCredits(status.buildCredits));
  };

  useEffect(() => {
    loadCredits();
  }, []);

  useEffect(() => {
    if (!isLoading && !isAuthenticated) navigate("/auth?next=/build");
  }, [isAuthenticated, isLoading, navigate]);

  if (isLoading || !isAuthenticated) return null; // Prevent flashing the UI

  const updateForm = (key: string, value: any) => setFormData(p => ({ ...p, [key]: value }));

  const handleAddExp = () => setFormData(p => ({ ...p, experience: [...p.experience, { id: Date.now(), title: "", company: "", duration: "", details: "" }] }));
  const handleExpChange = (id: number, field: string, value: string) => {
    setFormData(p => ({ ...p, experience: p.experience.map(e => e.id === id ? { ...e, [field]: value } : e) }));
  };

  const handleBuild = async () => {
    if (bldCredits <= 0) {
      setShowPaywall(true);
      return;
    }

    setIsBuilding(true);
    setError("");
    try {
      // Consume a credit
      const used = await useBuildCredit();
      if (!used) throw new Error("Not enough credits.");
      loadCredits(); // Refresh local count

      const generated = await buildResumeFromScratch(formData, setProgress);
      setResult(generated);
      
      // Save to Firebase
      const { db } = await import("~/lib/firebase");
      const { doc, setDoc } = await import("firebase/firestore");
      if (user) {
        await setDoc(doc(db, "resumes", generated.resumeId), {
          id: generated.resumeId,
          userId: user.uid,
          companyName: "Built From Scratch",
          jobTitle: formData.targetJob,
          jobDescription: formData.jobDescription,
          imagePath: "",
          resumePath: "",
          resumeText: "Generated by AI Builder",
          feedback: null, // No initial feedback needed
          optimization: generated,
          createdAt: generated.createdAt
        });
      }
    } catch (e: any) {
      setError(e.message || "Failed to generate resume.");
    } finally {
      setIsBuilding(false);
    }
  };

  return (
    <div className="page-shell">
      <Navbar />

      <div style={{ position: "fixed", inset: 0, zIndex: -1 }}>
        <img src="/images/img2.jpeg" alt="Background" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
        <div style={{ position: "absolute", inset: 0, background: "rgba(247, 244, 239, 0.5)" }} />
      </div>

      <section style={{ padding: "4rem 2rem 8rem", maxWidth: 900, margin: "0 auto", position: "relative" }}>
        
        {/* If result is ready, show it! */}
        {result ? (
          <div>
            <div style={{ textAlign: "center", marginBottom: "3rem" }}>
              <span className="section-label">Success!</span>
              <h1 style={{ margin: "0.5rem 0" }}>Your AI Résumé is Ready</h1>
              <p style={{ color: "var(--color-stone)", fontSize: "1.1rem" }}>We generated a completely unique design and rewrote your bullets for maximum impact.</p>
              <button onClick={() => window.location.reload()} className="btn-secondary" style={{ marginTop: "1rem" }}>Build Another</button>
            </div>
            
            <div className="card-elevated" style={{ padding: "3rem" }}>
               {/* We reuse OptimizedResumeView but hide the original image comparison by passing empty strings */}
               <OptimizedResumeView 
                 optimization={result} 
                 jobTitle={formData.targetJob} 
               />
            </div>
          </div>
        ) : isBuilding ? (
          /* Loading Screen */
          <div className="card-elevated" style={{ padding: "6rem 3rem", textAlign: "center", display: "flex", flexDirection: "column", alignItems: "center", gap: "2rem" }}>
             <div style={{ width: 60, height: 60, borderRadius: "100%", border: "3px solid var(--color-taupe-light)", borderTopColor: "var(--color-olive)", animation: "spin 1s linear infinite" }} />
             <div>
               <h2 style={{ margin: "0 0 0.5rem" }}>Forging your elite résumé...</h2>
               <p style={{ color: "var(--color-stone)", fontSize: "1.1rem" }}>{progress?.message || "Initializing AI engine..."}</p>
             </div>
          </div>
        ) : (
          /* Form Wizard */
          <>
            <div style={{ textAlign: "center", marginBottom: "3rem" }} className="anim-fade-up">
              <span className="section-label">AI Resume Builder</span>
              <h1 style={{ fontSize: "clamp(2rem,4vw,3.5rem)", margin: "0.5rem 0 1rem" }}>Create from Scratch</h1>
              <p style={{ maxWidth: 500, margin: "0 auto", fontSize: "1rem" }}>Dump your raw details below. Our 70B AI engine will rewrite it into a top 1% FAANG-style résumé with a unique visual theme.</p>
            </div>

            <div className="card-elevated anim-fade-up anim-delay-1" style={{ padding: "3rem 3.5rem" }}>
              
              {/* Wizard Nav */}
              <div style={{ display: "flex", gap: "1rem", marginBottom: "3rem", borderBottom: "1px solid rgba(196,181,160,0.2)", paddingBottom: "1rem" }}>
                {[1, 2, 3].map(s => (
                  <button key={s} onClick={() => setStep(s)} style={{ 
                    background: "none", border: "none", cursor: "pointer",
                    fontSize: "0.9rem", fontWeight: step === s ? 700 : 400,
                    color: step === s ? "var(--color-espresso)" : "var(--color-stone)" 
                  }}>
                    Step {s}
                  </button>
                ))}
              </div>

              {error && (
                <div style={{ padding: "1rem", background: "var(--color-clay-light)", color: "var(--color-clay)", borderRadius: "1rem", marginBottom: "2rem" }}>
                  {error}
                </div>
              )}

              {/* STEP 1 */}
              {step === 1 && (
                <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                  <h3 style={{ margin: 0 }}>Personal & Target Details</h3>
                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.5rem" }}>
                    <div className="field">
                      <label>Full Name</label>
                      <input value={formData.fullName} onChange={e => updateForm("fullName", e.target.value)} placeholder="Jane Doe" />
                    </div>
                    <div className="field">
                      <label>Target Job Title</label>
                      <input value={formData.targetJob} onChange={e => updateForm("targetJob", e.target.value)} placeholder="e.g. Senior Software Engineer" />
                    </div>
                    <div className="field">
                      <label>Email</label>
                      <input value={formData.email} onChange={e => updateForm("email", e.target.value)} placeholder="jane@example.com" />
                    </div>
                    <div className="field">
                      <label>Phone / Location</label>
                      <input value={formData.phone} onChange={e => updateForm("phone", e.target.value)} placeholder="(555) 123-4567 • New York, NY" />
                    </div>
                  </div>
                  <div className="field">
                    <label>Raw Summary / Intro Ideas (Optional)</label>
                    <textarea value={formData.summary} onChange={e => updateForm("summary", e.target.value)} rows={3} placeholder="Just dump some ideas about yourself here. The AI will write the actual summary." />
                  </div>
                  <button onClick={() => setStep(2)} className="btn-primary" style={{ alignSelf: "flex-end", marginTop: "1rem" }}>Next: Experience</button>
                </div>
              )}

              {/* STEP 2 */}
              {step === 2 && (
                <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                    <h3 style={{ margin: 0 }}>Work Experience</h3>
                    <button onClick={handleAddExp} className="btn-secondary" style={{ fontSize: "0.75rem", padding: "0.4rem 0.8rem" }}>+ Add Job</button>
                  </div>
                  
                  {formData.experience.map((exp, i) => (
                    <div key={exp.id} style={{ background: "var(--color-cream-warm)", padding: "1.5rem", borderRadius: "1rem", display: "flex", flexDirection: "column", gap: "1rem" }}>
                      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
                        <div className="field">
                          <label>Job Title</label>
                          <input value={exp.title} onChange={e => handleExpChange(exp.id, "title", e.target.value)} placeholder="Software Engineer" />
                        </div>
                        <div className="field">
                          <label>Company</label>
                          <input value={exp.company} onChange={e => handleExpChange(exp.id, "company", e.target.value)} placeholder="Google" />
                        </div>
                        <div className="field">
                          <label>Duration</label>
                          <input value={exp.duration} onChange={e => handleExpChange(exp.id, "duration", e.target.value)} placeholder="Jan 2020 - Present" />
                        </div>
                      </div>
                      <div className="field">
                        <label>What did you do? (Be casual, AI will fix it)</label>
                        <textarea value={exp.details} onChange={e => handleExpChange(exp.id, "details", e.target.value)} rows={3} placeholder="I worked on the backend API using Node.js and made it 50% faster." />
                      </div>
                    </div>
                  ))}
                  
                  <div style={{ display: "flex", justifyContent: "space-between", marginTop: "1rem" }}>
                    <button onClick={() => setStep(1)} className="btn-secondary">Back</button>
                    <button onClick={() => setStep(3)} className="btn-primary">Next: Skills & Finish</button>
                  </div>
                </div>
              )}

              {/* STEP 3 */}
              {step === 3 && (
                <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                  <h3 style={{ margin: 0 }}>Skills & Education</h3>
                  <div className="field">
                    <label>Skills (comma separated)</label>
                    <textarea value={formData.skills} onChange={e => updateForm("skills", e.target.value)} rows={2} placeholder="React, TypeScript, Project Management, Agile..." />
                  </div>
                  
                  <div style={{ background: "var(--color-cream-warm)", padding: "1.5rem", borderRadius: "1rem", display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
                    <div className="field">
                      <label>Degree</label>
                      <input value={formData.education[0].degree} onChange={e => {
                        const newEd = [...formData.education]; newEd[0].degree = e.target.value; updateForm("education", newEd);
                      }} placeholder="B.S. Computer Science" />
                    </div>
                    <div className="field">
                      <label>Institution</label>
                      <input value={formData.education[0].institution} onChange={e => {
                        const newEd = [...formData.education]; newEd[0].institution = e.target.value; updateForm("education", newEd);
                      }} placeholder="Stanford University" />
                    </div>
                  </div>

                  <div style={{ display: "flex", justifyContent: "space-between", marginTop: "2rem" }}>
                    <button onClick={() => setStep(2)} className="btn-secondary">Back</button>
                    <button onClick={handleBuild} className="btn-primary" style={{ background: "var(--color-olive)", border: "none", color: "#fff" }}>
                      {bldCredits > 0 ? "Generate Resume Now" : "Unlock AI Builder"}
                      <svg width="15" height="15" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}><path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                    </button>
                  </div>
                </div>
              )}

            </div>
          </>
        )}
      </section>

      {showPaywall && (
        <PaywallModal 
          feature="build-ai"
          onClose={() => setShowPaywall(false)} 
          onSuccess={() => {
            loadCredits();
            setShowPaywall(false);
            setTimeout(() => {
              handleBuild();
            }, 0);
          }} 
          userName={user?.displayName || user?.email || ""} 
          userEmail={user?.email || ""}
        />
      )}
    </div>
  );
}
