import { useState, useEffect } from "react";
import Navbar from "~/components/Navbar";
import { useAppStore } from "~/lib/store";
import { useNavigate } from "react-router";
import { buildResumeFromScratch, type BuildProgress } from "~/lib/resume-builder";
import OptimizedResumeView from "~/components/OptimizedResumeView";
import PaywallModal from "~/components/PaywallModal";
import { checkPremiumStatus, useBuildCredit } from "~/lib/premium";

export const meta = () => ([
  { title: "Resumate — AI Resume Builder" },
  { name: "description", content: "Build a highly optimized resume from scratch using AI." },
]);

export default function BuildResume() {
  const { isAuthenticated, isLoading, user } = useAppStore();
  const navigate = useNavigate();

  const [step, setStep] = useState(1);
  const [isBuilding, setIsBuilding] = useState(false);
  const [progress, setProgress] = useState<BuildProgress | null>(null);
  const [result, setResult] = useState<ResumeOptimization | null>(null);
  const [error, setError] = useState("");

  const [bldCredits, setBldCredits] = useState(0);
  const [showPaywall, setShowPaywall] = useState(false);

  const [formData, setFormData] = useState({
    fullName: "", email: "", phone: "", location: "", linkedin: "",
    targetJob: "", jobDescription: "", summary: "",
    skills: "",
    experience: [{ id: 1, title: "", company: "", duration: "", details: "" }],
    education: [{ id: 1, degree: "", institution: "", year: "" }],
    projects: [{ id: 1, name: "", technologies: "", details: "" }],
  });

  const loadCredits = () => {
    checkPremiumStatus().then(status => setBldCredits(status.buildCredits));
  };

  useEffect(() => { loadCredits(); }, []);
  useEffect(() => {
    if (!isLoading && !isAuthenticated) navigate("/auth?next=/build");
  }, [isAuthenticated, isLoading, navigate]);

  if (isLoading || !isAuthenticated) return null;

  const updateForm = (key: string, value: any) => setFormData(p => ({ ...p, [key]: value }));

  const handleAddExp = () => setFormData(p => ({
    ...p, experience: [...p.experience, { id: Date.now(), title: "", company: "", duration: "", details: "" }],
  }));

  const handleExpChange = (id: number, field: string, value: string) => {
    setFormData(p => ({ ...p, experience: p.experience.map(e => e.id === id ? { ...e, [field]: value } : e) }));
  };

  const handleBuild = async () => {
    if (bldCredits <= 0) { setShowPaywall(true); return; }
    setIsBuilding(true);
    setError("");
    try {
      const used = await useBuildCredit();
      if (!used) throw new Error("Not enough credits.");
      loadCredits();
      const generated = await buildResumeFromScratch(formData, setProgress);
      setResult(generated);
      const { db } = await import("~/lib/firebase");
      const { doc, setDoc } = await import("firebase/firestore");
      if (user) {
        await setDoc(doc(db, "resumes", generated.resumeId), {
          id: generated.resumeId,
          userId: user.uid,
          companyName: "Built From Scratch",
          jobTitle: formData.targetJob,
          jobDescription: formData.jobDescription,
          imagePath: "",
          resumePath: "",
          resumeText: "Generated by AI Builder",
          feedback: null,
          optimization: generated,
          createdAt: generated.createdAt,
        });
      }
    } catch (e: any) {
      setError(e.message || "Failed to generate resume.");
    } finally {
      setIsBuilding(false);
    }
  };

  const inputStyle: React.CSSProperties = {
    width: "100%",
    padding: "0.75rem 0.875rem",
    borderRadius: "0.65rem",
    border: "1px solid rgba(184,168,152,0.4)",
    background: "var(--color-ivory-warm)",
    color: "var(--color-espresso)",
    fontSize: "0.88rem",
    fontFamily: "var(--font-sans)",
    outline: "none",
    transition: "border-color 0.2s, box-shadow 0.2s",
  };

  const textareaStyle: React.CSSProperties = { ...inputStyle, resize: "vertical" };

  const focusStyle = {
    onFocus: (e: React.FocusEvent<any>) => {
      e.target.style.borderColor = "var(--color-taupe-dark)";
      e.target.style.boxShadow = "0 0 0 3px rgba(154,136,120,0.12)";
    },
    onBlur: (e: React.FocusEvent<any>) => {
      e.target.style.borderColor = "rgba(184,168,152,0.4)";
      e.target.style.boxShadow = "none";
    },
  };

  const labelStyle: React.CSSProperties = {
    fontSize: "0.65rem",
    fontWeight: 600,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--color-stone)",
    display: "block",
    marginBottom: "0.375rem",
    fontFamily: "var(--font-sans)",
  };

  const STEPS_LABELS = ["Personal", "Experience", "Skills & Edu"];
  const progressPct = (step / 3) * 100;

  return (
    <div className="page-shell">
      <Navbar />

      <div style={{ position: "fixed", inset: 0, zIndex: -1, pointerEvents: "none" }}>
        <img src="/images/img2.jpeg" alt="Background" style={{ width: "100%", height: "100%", objectFit: "cover", opacity: 0.8 }} />
        <div style={{ position: "absolute", inset: 0, background: "rgba(247, 244, 239, 0.6)" }} />
      </div>

      {/* ── Page header ── */}
      <div style={{
        borderBottom: "1px solid rgba(184,168,152,0.18)",
        padding: "0 2.5rem",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        height: 60,
        background: "var(--color-paper)",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
          <span style={{ fontFamily: "var(--font-serif)", fontSize: "0.95rem", color: "var(--color-espresso)", letterSpacing: "0.04em" }}>
            AI Resume Builder
          </span>
          <span style={{ width: 1, height: 16, background: "rgba(184,168,152,0.4)" }} />
          {/* Step progress */}
          <div style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
            {STEPS_LABELS.map((label, i) => (
              <button key={i}
                onClick={() => !isBuilding && setStep(i + 1)}
                style={{
                  background: "none", border: "none", cursor: "pointer",
                  padding: "0.25rem 0",
                  fontSize: "0.72rem",
                  fontWeight: step === i + 1 ? 600 : 400,
                  color: step === i + 1 ? "var(--color-espresso)" : step > i + 1 ? "var(--color-sage-dark)" : "var(--color-stone)",
                  fontFamily: "var(--font-sans)",
                  textDecoration: step === i + 1 ? "underline" : "none",
                  textUnderlineOffset: "3px",
                  transition: "color 0.2s",
                }}
              >
                {step > i + 1 ? "✓ " : ""}{label}
              </button>
            ))}
          </div>
        </div>

        {/* Progress bar */}
        <div style={{ width: 120, height: 3, background: "rgba(184,168,152,0.3)", borderRadius: "100px", overflow: "hidden" }}>
          <div style={{
            height: "100%",
            width: `${progressPct}%`,
            background: "var(--color-espresso)",
            borderRadius: "100px",
            transition: "width 0.4s ease",
          }} />
        </div>
      </div>

      {/* ── Main content ── */}
      <div style={{
        maxWidth: 1200,
        margin: "0 auto",
        padding: "2.5rem 2rem 6rem",
        display: "grid",
        gridTemplateColumns: "1fr 380px",
        gap: "2rem",
        alignItems: "start",
      }}
        className="build-layout"
      >
        {/* ── LEFT: Form ── */}
        <div>
          {result ? (
            /* Success */
            <div>
              <div style={{ textAlign: "center", marginBottom: "2.5rem" }}>
                <div style={{
                  width: 56, height: 56,
                  borderRadius: "100%",
                  background: "var(--color-sage-light)",
                  display: "flex", alignItems: "center", justifyContent: "center",
                  margin: "0 auto 1.25rem",
                }}>
                  <svg width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="var(--color-sage-dark)" strokeWidth={2.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                </div>
                <span className="section-label">Success!</span>
                <h2 style={{ fontSize: "1.8rem", marginTop: "0.25rem", marginBottom: "0.75rem" }}>Your AI Résumé is Ready</h2>
                <p style={{ maxWidth: 440, margin: "0 auto", fontSize: "1rem" }}>
                  We generated a completely unique design and rewrote your bullets for maximum impact.
                </p>
                <button onClick={() => window.location.reload()} className="btn-secondary" style={{ marginTop: "1.5rem" }}>
                  Build Another
                </button>
              </div>
              <div className="card-elevated" style={{ padding: "2.5rem" }}>
                <OptimizedResumeView optimization={result} jobTitle={formData.targetJob} />
              </div>
            </div>
          ) : isBuilding ? (
            /* Building state */
            <div className="card-elevated" style={{
              padding: "5rem 3rem",
              textAlign: "center",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: "1.75rem",
            }}>
              <div style={{
                width: 60, height: 60,
                borderRadius: "100%",
                border: "2px solid rgba(184,168,152,0.3)",
                borderTopColor: "var(--color-espresso)",
                animation: "spin 1s linear infinite",
              }} />
              <div>
                <h3 style={{ marginBottom: "0.5rem" }}>Forging your elite résumé…</h3>
                <p style={{ fontSize: "1rem" }}>{progress?.message || "Initializing AI engine…"}</p>
              </div>
            </div>
          ) : (
            /* Form wizard */
            <div className="card-elevated" style={{ padding: "2.5rem" }}>
              {error && (
                <div style={{
                  padding: "0.875rem 1.125rem",
                  background: "var(--color-clay-light)",
                  border: "1px solid rgba(168,92,74,0.2)",
                  borderRadius: "0.75rem",
                  color: "var(--color-clay)",
                  fontSize: "0.85rem",
                  marginBottom: "1.5rem",
                }}>
                  {error}
                </div>
              )}

              {/* STEP 1 */}
              {step === 1 && (
                <div style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}>
                  <h3 style={{ fontSize: "1.2rem" }}>Personal & Target Details</h3>

                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.25rem" }}>
                    <div>
                      <label style={labelStyle}>Full Name</label>
                      <input style={inputStyle} {...focusStyle} value={formData.fullName} onChange={e => updateForm("fullName", e.target.value)} placeholder="Jane Doe" />
                    </div>
                    <div>
                      <label style={labelStyle}>Target Job Title</label>
                      <input style={inputStyle} {...focusStyle} value={formData.targetJob} onChange={e => updateForm("targetJob", e.target.value)} placeholder="e.g. Senior Engineer" />
                    </div>
                    <div>
                      <label style={labelStyle}>Email</label>
                      <input style={inputStyle} {...focusStyle} value={formData.email} onChange={e => updateForm("email", e.target.value)} placeholder="jane@example.com" />
                    </div>
                    <div>
                      <label style={labelStyle}>Phone / Location</label>
                      <input style={inputStyle} {...focusStyle} value={formData.phone} onChange={e => updateForm("phone", e.target.value)} placeholder="(555) 123-4567 · New York" />
                    </div>
                    <div style={{ gridColumn: "1/-1" }}>
                      <label style={labelStyle}>LinkedIn (optional)</label>
                      <input style={inputStyle} {...focusStyle} value={formData.linkedin} onChange={e => updateForm("linkedin", e.target.value)} placeholder="linkedin.com/in/jane-smith" />
                    </div>
                  </div>

                  <div>
                    <label style={labelStyle}>Raw Summary / Intro Ideas (optional)</label>
                    <textarea style={{ ...textareaStyle, minHeight: 80 }} {...focusStyle} value={formData.summary} onChange={e => updateForm("summary", e.target.value)} placeholder="Just dump some ideas about yourself. The AI will write the actual summary." rows={3} />
                  </div>

                  <div style={{ display: "flex", justifyContent: "flex-end", marginTop: "0.5rem" }}>
                    <button onClick={() => setStep(2)} className="btn-primary">
                      Next: Experience
                      <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
                      </svg>
                    </button>
                  </div>
                </div>
              )}

              {/* STEP 2 */}
              {step === 2 && (
                <div style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                    <h3 style={{ fontSize: "1.2rem" }}>Work Experience</h3>
                    <button onClick={handleAddExp} className="btn-secondary" style={{ fontSize: "0.72rem", padding: "0.4rem 0.875rem" }}>
                      + Add Job
                    </button>
                  </div>

                  {formData.experience.map((exp, _) => (
                    <div key={exp.id} style={{
                      background: "var(--color-ivory-warm)",
                      borderRadius: "0.875rem",
                      padding: "1.25rem",
                      border: "1px solid rgba(184,168,152,0.3)",
                      display: "flex",
                      flexDirection: "column",
                      gap: "0.875rem",
                    }}>
                      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.875rem" }}>
                        <div>
                          <label style={labelStyle}>Job Title</label>
                          <input style={inputStyle} {...focusStyle} value={exp.title} onChange={e => handleExpChange(exp.id, "title", e.target.value)} placeholder="Software Engineer" />
                        </div>
                        <div>
                          <label style={labelStyle}>Company</label>
                          <input style={inputStyle} {...focusStyle} value={exp.company} onChange={e => handleExpChange(exp.id, "company", e.target.value)} placeholder="Google" />
                        </div>
                        <div style={{ gridColumn: "1/-1" }}>
                          <label style={labelStyle}>Duration</label>
                          <input style={inputStyle} {...focusStyle} value={exp.duration} onChange={e => handleExpChange(exp.id, "duration", e.target.value)} placeholder="Jan 2020 – Present" />
                        </div>
                      </div>
                      <div>
                        <label style={labelStyle}>What did you do? (AI will polish it)</label>
                        <textarea style={{ ...textareaStyle, minHeight: 80 }} {...focusStyle} value={exp.details} onChange={e => handleExpChange(exp.id, "details", e.target.value)} rows={3} placeholder="I worked on the backend API using Node.js and made it 50% faster." />
                      </div>
                    </div>
                  ))}

                  <div style={{ display: "flex", justifyContent: "space-between", marginTop: "0.5rem" }}>
                    <button onClick={() => setStep(1)} className="btn-secondary">← Back</button>
                    <button onClick={() => setStep(3)} className="btn-primary">
                      Next: Skills & Finish
                      <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
                      </svg>
                    </button>
                  </div>
                </div>
              )}

              {/* STEP 3 */}
              {step === 3 && (
                <div style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}>
                  <h3 style={{ fontSize: "1.2rem" }}>Skills & Education</h3>

                  <div>
                    <label style={labelStyle}>Skills (comma separated)</label>
                    <textarea style={{ ...textareaStyle, minHeight: 64 }} {...focusStyle} value={formData.skills} onChange={e => updateForm("skills", e.target.value)} rows={2} placeholder="React, TypeScript, Project Management, Agile…" />
                  </div>

                  <div style={{
                    background: "var(--color-ivory-warm)",
                    borderRadius: "0.875rem",
                    padding: "1.25rem",
                    border: "1px solid rgba(184,168,152,0.3)",
                    display: "grid",
                    gridTemplateColumns: "1fr 1fr",
                    gap: "0.875rem",
                  }}>
                    <div style={{ gridColumn: "1/-1" }}>
                      <p style={{ margin: "0 0 0.75rem", fontSize: "0.8rem", fontWeight: 600, color: "var(--color-espresso)", letterSpacing: "0.04em" }}>Education</p>
                    </div>
                    <div>
                      <label style={labelStyle}>Degree</label>
                      <input style={inputStyle} {...focusStyle} value={formData.education[0].degree} onChange={e => {
                        const newEd = [...formData.education]; newEd[0].degree = e.target.value; updateForm("education", newEd);
                      }} placeholder="B.S. Computer Science" />
                    </div>
                    <div>
                      <label style={labelStyle}>Institution</label>
                      <input style={inputStyle} {...focusStyle} value={formData.education[0].institution} onChange={e => {
                        const newEd = [...formData.education]; newEd[0].institution = e.target.value; updateForm("education", newEd);
                      }} placeholder="Stanford University" />
                    </div>
                  </div>

                  <div>
                    <label style={labelStyle}>Target Job Description (optional, improves quality)</label>
                    <textarea style={{ ...textareaStyle, minHeight: 100 }} {...focusStyle} value={formData.jobDescription} onChange={e => updateForm("jobDescription", e.target.value)} rows={4} placeholder="Paste the job description you're targeting here…" />
                  </div>

                  <div style={{ display: "flex", justifyContent: "space-between", marginTop: "0.5rem" }}>
                    <button onClick={() => setStep(2)} className="btn-secondary">← Back</button>
                    <button onClick={handleBuild} className="btn-primary">
                      {bldCredits > 0 ? "Generate Resume Now" : "Unlock AI Builder"}
                      <svg width="15" height="15" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
                      </svg>
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* ── RIGHT: Preview Panel ── */}
        <div style={{ position: "sticky", top: 80 }}>
          <div className="card" style={{ overflow: "hidden" }}>
            {/* Preview header */}
            <div style={{
              padding: "1rem 1.5rem",
              borderBottom: "1px solid rgba(184,168,152,0.2)",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
            }}>
              <span style={{ fontSize: "0.72rem", fontWeight: 600, letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-stone)" }}>
                Live Preview
              </span>
              <span style={{ fontSize: "0.68rem", color: "var(--color-stone-light)" }}>
                {STEPS_LABELS[step - 1]}
              </span>
            </div>

            {/* Paper resume preview */}
            <div style={{
              padding: "1.75rem",
              background: "var(--color-ivory-warm)",
              minHeight: 400,
            }}>
              {/* Document paper */}
              <div style={{
                background: "#FFFFFF",
                borderRadius: "0.5rem",
                padding: "1.5rem",
                boxShadow: "0 2px 12px rgba(28,23,19,0.08)",
                minHeight: 360,
              }}>
                {/* Name */}
                <div style={{ marginBottom: "1.25rem", paddingBottom: "0.75rem", borderBottom: "1px solid rgba(0,0,0,0.06)" }}>
                  <div style={{
                    height: formData.fullName ? "auto" : 14,
                    width: formData.fullName ? "auto" : "65%",
                    borderRadius: "100px",
                    background: formData.fullName ? "transparent" : "rgba(184,168,152,0.3)",
                    fontFamily: formData.fullName ? "Georgia, serif" : undefined,
                    fontSize: "1.1rem",
                    fontWeight: 700,
                    color: "#111",
                    marginBottom: "0.25rem",
                  }}>
                    {formData.fullName || ""}
                  </div>
                  {formData.targetJob && (
                    <p style={{ fontSize: "0.75rem", color: "#666", margin: 0 }}>{formData.targetJob}</p>
                  )}
                  {formData.email && (
                    <p style={{ fontSize: "0.65rem", color: "#888", margin: "0.25rem 0 0" }}>
                      {formData.email}{formData.phone ? ` · ${formData.phone}` : ""}
                    </p>
                  )}
                </div>

                {/* Line placeholders */}
                {[80, 95, 70, 85, 60, 75, 90, 65].map((w, i) => (
                  <div key={i} style={{
                    height: 5,
                    width: `${w}%`,
                    borderRadius: "100px",
                    background: "rgba(184,168,152,0.25)",
                    marginBottom: "0.5rem",
                  }} />
                ))}

                {/* AI badge */}
                <div style={{
                  marginTop: "1.25rem",
                  display: "inline-flex",
                  alignItems: "center",
                  gap: "0.375rem",
                  padding: "0.25rem 0.625rem",
                  borderRadius: "100px",
                  background: "rgba(184,168,152,0.15)",
                  border: "1px solid rgba(184,168,152,0.35)",
                }}>
                  <svg width="10" height="10" fill="none" viewBox="0 0 24 24" stroke="var(--color-stone)" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                  <span style={{ fontSize: "0.6rem", color: "var(--color-stone)", fontFamily: "var(--font-sans)", letterSpacing: "0.06em" }}>
                    AI GENERATED
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* AI Tip card */}
          <div className="card" style={{ marginTop: "1rem", padding: "1.25rem" }}>
            <div style={{ display: "flex", alignItems: "flex-start", gap: "0.75rem" }}>
              <div style={{
                width: 30, height: 30,
                borderRadius: "0.5rem",
                background: "var(--color-ivory-warm)",
                border: "1px solid rgba(184,168,152,0.4)",
                display: "flex", alignItems: "center", justifyContent: "center",
                flexShrink: 0,
              }}>
                <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="var(--color-warm-mid)" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
              <div>
                <p style={{ fontSize: "0.72rem", fontWeight: 600, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-stone)", marginBottom: "0.25rem" }}>
                  AI Tip
                </p>
                <p style={{ fontSize: "0.82rem", color: "var(--color-brown)", lineHeight: 1.55, margin: 0 }}>
                  {step === 1 && "Add your target job title to help the AI tailor every section of your résumé."}
                  {step === 2 && "Be specific with impact numbers — the AI will rewrite them into FAANG-style power bullets."}
                  {step === 3 && "Adding the job description allows the AI to target the exact keywords recruiters search for."}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Paywall */}
      {showPaywall && (
        <PaywallModal
          feature="build-ai"
          onClose={() => setShowPaywall(false)}
          onSuccess={() => {
            loadCredits();
            setShowPaywall(false);
            setTimeout(() => handleBuild(), 0);
          }}
          userName={user?.displayName || user?.email || ""}
          userEmail={user?.email || ""}
        />
      )}
    </div>
  );
}
